### ISSUE TITLE
Disk detection on linux

### ISSUE THREAD

**Issue by OctoOsmo** [int0h/npm-hddSpace#2]
On windows it works fine, but on my ubuntu 16.04.2 I have this output:

>node hdd.js
{ parts:
   [ { free: 'NaN PB', size: 'NaN PB', place: 'v', mountOn: 'v' },
     { free: 'NaN PB', size: 'NaN PB', place: 'n', mountOn: 'n' },
     { free: 'NaN PB', size: 'NaN PB', place: '/', mountOn: '/' },
     { free: 'NaN PB', size: 'NaN PB', place: 'm', mountOn: 'm' },
     { free: 'NaN PB', size: 'NaN PB', place: 'k', mountOn: 'k' },
     { free: 'NaN PB', size: 'NaN PB', place: 'p', mountOn: 'p' },
     { free: 'NaN PB', size: 'NaN PB', place: 's', mountOn: 's' },
     { free: 'NaN PB', size: 'NaN PB', place: 'o', mountOn: 'o' },
     { free: 'NaN PB', size: 'NaN PB', place: 's', mountOn: 's' },
     { free: 'NaN PB', size: 'NaN PB', place: '0', mountOn: '0' },
     { free: 'NaN PB', size: 'NaN PB', place: '1', mountOn: '1' } ],
  total: { free: 'NaN PB', size: 'NaN PB' } }

here is hdd.js:
var hddSpace = require('hdd-space');
hddSpace({ format: 'auto' }, function (info) {
    console.log(info);
});

**Comment by OctoOsmo** [comment]
p.s.
> node -v
v4.2.6

**Comment by int0h** [comment]
Could you please provide the output of `df -Pk` on your machine? (I won't have access to ubuntu for a few days)

**Comment by OctoOsmo** [comment]
Sure, here it is:
[df -pk.txt](https://github.com/int0h/npm-hddSpace/files/1112315/df.-pk.txt)

**Comment by OctoOsmo** [comment]
Table markdown of  df -Pk output:

Файл.система | 1024-блоков | Использовано | Доступно | Вместимость | Cмонтировано в
------------ | ------------- | ------------- | ------------- | ------------- | ------------- 
udev | 2485944 | 0 | 2485944 | 0% | /dev
tmpfs | 507804 | 60492 | 447312 | 12% | /run
/dev/sda1 | 71631200 | 48091380 | 19878048 | 71% | /
tmpfs | 2539016 | 1616 | 2537400 | 1% | /dev/shm
tmpfs | 5120 | 4 | 5116 | 1% | /run/lock
tmpfs | 2539016 | 0 | 2539016 | 0% | /sys/fs/cgroup
/dev/sdc | 240234168 | 188729228 | 39278628 | 83% | /media/Downloads
/dev/sdb | 307535312 | 227899592 | 63990776 | 79% | /media/Video
cgmfs | 100 | 0 | 100 | 0% | /run/cgmanager/fs
tmpfs | 507804 | 0 | 507804 | 0% | /run/user/1000
tmpfs | 507804 | 40 | 507764 | 1% | /run/user/1001

**Comment by OctoOsmo** [comment]
I've found a root cause:
Russin locale cause this problem.

**Comment by OctoOsmo** [comment]
But why it locale depenndent, can you fix it?

**Comment by int0h** [comment]
I hope I fix the problem in a separate branch. You can test it and use via:
```
npm i --save https://github.com/int0h/npm-hddSpace.git#migrate-to-column-parser
```
Please let me know if it fixes your problem!

I'm going to refactor it a little bit more and write tests. So these changes are going to be in master (and npm) in a week or two. I published the branch to provide the fix as soon as possible - so you don't need to wait.

What was the problem: this package works via parsing output of terminal commands (it's not the best solution but it allows to avoid binary dependencies). Before I used header names (the first line if the output) to find certain values (parsing the output is not as trivial as it seems). So.. it failed to find proper header in the output of your command. Now it uses indexes instead of names and the great lib https://github.com/sindresorhus/parse-columns.

P.s. thanks for the report!

**Comment by OctoOsmo** [comment]
Now it works fine. Thank you!

**Comment by int0h** [comment]
@OctoOsmo Hello! I want to notify you that I've finally updated `hdd-space` package. (I've added some test, coverage etc.; There is a list of changes in readme) Your system should be supported either from master or npm. You may consider updating the module. If you decide to do so, I'll be glad to receive any feedback. 
P.s. Now it support Promises (there are some new examples in readme also)
